name: data_grid_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  syncfusion_flutter_datagrid:
    git:
      url: https://buildautomation:Coolcomp299@gitlab.syncfusion.com/essential-studio/flutter-datagrid
      path: flutter_datagrid/syncfusion_flutter_datagrid
      branch: development
      ref: development


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - ipl_time_table.json
     - images/
